<a href="https://colab.research.google.com/github/dianasimon760-boop/laguardiadataclass/blob/main/DSimonFinalExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1A.LOAD DATASET MELBOURNE HOUSING
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
from pathlib import Path

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

sns.set_style('whitegrid')

In [2]:
#1B.PULL IN DATA SET MELBOURNE HOUSING USING GITHUB
df = pd.read_csv("https://raw.githubusercontent.com/dianasimon760-boop/laguardiadataclass/refs/heads/main/Melbourne_Housing%20-%20Melbourne_Housing.csv", low_memory=False)

In [3]:
#2A.VIEW MELBOURNE HOUSING DATASET FIRST FIVE ROWS
df.head()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,Airport West,3,t,Nelson,03-09-2016,13.50,3042.00,3.00,2.00,1.00,303.00,225,2016.00,Western Metropolitan,3464,840000
1,Albert Park,2,h,hockingstuart,03-09-2016,3.30,3206.00,2.00,1.00,0.00,120.00,82,1900.00,Southern Metropolitan,3280,1275000
2,Albert Park,2,h,Thomson,03-09-2016,3.30,3206.00,2.00,1.00,0.00,159.00,inf,NaN,Southern Metropolitan,3280,1455000
3,Alphington,4,h,Brace,03-09-2016,6.40,3078.00,3.00,2.00,4.00,853.00,263,1930.00,Northern Metropolitan,2211,2000000
4,Alphington,3,h,Jellis,03-09-2016,6.40,3078.00,3.00,2.00,2.00,208.00,inf,2013.00,Northern Metropolitan,2211,1110000

In [4]:
#2B. VIEW MELBOURNE HOUSING DATASET LAST FIVE ROWS
df.tail(5)

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
27109,Noble Park,3,h,C21,30-09-2017,22.70,3174.00,3.00,1.00,6.00,569.00,130,1959.00,South-Eastern Metropolitan,11806,627500
27110,Reservoir,3,u,RW,30-09-2017,12.00,3073.00,3.00,1.00,1.00,NaN,105,1990.00,Northern Metropolitan,21650,475000
27111,Roxburgh Park,4,h,Raine,30-09-2017,20.60,3064.00,4.00,2.00,2.00,NaN,225,1995.00,Northern Metropolitan,5833,591000
27112,Springvale South,3,h,Harcourts,30-09-2017,22.20,3172.00,3.00,2.00,1.00,544.00,NaN,NaN,South-Eastern Metropolitan,4054,780500
27113,Westmeadows,4,h,Barry,30-09-2017,16.50,3049.00,4.00,2.00,6.00,813.00,140,1960.00,Northern Metropolitan,2474,791000

In [5]:
#3A. WHAT IS THE COUNT IN COLUMNS?
####There are 16 columns in Melbourne Dataset
#3B. WHAT ARE THE ROWS COUNT?
####Suburb, Rooms, Type, SellerG, Date, Regionname, Property Count and Price has a row count of 27,114
####Distance has a row count of 27,113
####Bedroom has a row count of 20,678
####Bathroom has arow count of 20,672
####Car has a row count of 20,297
####Landsize has a row count of 17,873
#11  BuildingArea   10543
#12  YearBuilt      11985

#4. WHAT ARE THE DATATYPES IN MELBOURNE HOUSING DATASET?
#####dtypes: float64(7), int64(3), object(6)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  object
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10543 non-null  object
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: float64(7), int64(3), object(6)
memory usage: 3.3+ MB